ALTER TABLE BREWERY ADD CONSTRAINT FOREIGN KEY (region_id) REFERENCES REGION(region_id);

ALTER TABLE BEER_FOOD ADD CONSTRAINT FOREIGN KEY (food_id) REFERENCES FOOD_PAIRING(food_id);
ALTER TABLE BEER_FOOD ADD CONSTRAINT FOREIGN KEY (beer_id) REFERENCES BEER(beer_id);

ALTER TABLE BEER_FOR_SALE ADD CONSTRAINT FOREIGN KEY (beer_id) REFERENCES BEER(beer_id);
ALTER TABLE BEER_FOR_SALE ADD CONSTRAINT FOREIGN KEY (sales_id) REFERENCES SALES_LOCATION(sales_id);

ALTER TABLE BEER_IN_BARS ADD CONSTRAINT FOREIGN KEY (bar_id) REFERENCES BAR(bar_id);
ALTER TABLE BEER_IN_BARS ADD CONSTRAINT FOREIGN KEY (beer_id) REFERENCES BEER(beer_id);

ALTER TABLE BEER ADD CONSTRAINT FOREIGN KEY (style_id) REFERENCES BEER_STYLE(style_id);
ALTER TABLE BEER ADD CONSTRAINT FOREIGN KEY (brewery_id) REFERENCES BREWERY(brewery_id);
ALTER TABLE BEER ADD CONSTRAINT FOREIGN KEY (price_range_code) REFERENCES PRICE_RANGE(price_range_code);

ALTER TABLE BEER_FOR_SEASON ADD CONSTRAINT FOREIGN KEY (beer_id) REFERENCES BEER(beer_id);
ALTER TABLE BEER_FOR_SEASON ADD CONSTRAINT FOREIGN KEY (time_of_year_availability_id) REFERENCES SEASONAL_AVAILABILITY(time_of_year_availability_id);

ALTER TABLE LIKES ADD CONSTRAINT FOREIGN KEY (beer_id) REFERENCES BEER(beer_id);
ALTER TABLE LIKES ADD CONSTRAINT FOREIGN KEY (username) REFERENCES PERSON(username);
